#!/bin/bash
# NFT Platform Backend - Ubuntu Deployment Guide
# Deployment to: root@5.252.155.82

echo "=================================================="
echo "NFT Platform Backend - Ubuntu Setup Guide"
echo "=================================================="
echo ""
echo "Server: root@5.252.155.82"
echo "Database: PostgreSQL on same server"
echo ""

# Step 1: SSH into the server
echo "Step 1: Connect to your Ubuntu server"
echo "=========================================="
echo "Run this command on your Windows machine:"
echo ""
echo "  ssh root@5.252.155.82"
echo ""
echo "Enter your password when prompted"
echo ""
read -p "Press Enter once you're connected via SSH..."

# Step 2: Update system
echo ""
echo "Step 2: Update system packages"
echo "=========================================="
echo "Run these commands on the Ubuntu server:"
echo ""
echo "  sudo apt update"
echo "  sudo apt upgrade -y"
echo ""
read -p "Press Enter once completed..."

# Step 3: Install dependencies
echo ""
echo "Step 3: Install required packages"
echo "=========================================="
echo "Run this on Ubuntu server:"
echo ""
echo "  sudo apt install -y git python3.11 python3.11-venv python3-pip postgresql postgresql-client curl wget"
echo ""
read -p "Press Enter once completed..."

# Step 4: Create application user
echo ""
echo "Step 4: Create application user"
echo "=========================================="
echo "Run this on Ubuntu server:"
echo ""
echo "  sudo useradd -m -s /bin/bash nft_app"
echo "  sudo usermod -aG sudo nft_app"
echo ""
read -p "Press Enter once completed..."

# Step 5: Clone repository
echo ""
echo "Step 5: Clone NFT Platform repository"
echo "=========================================="
echo "Run these commands on Ubuntu server:"
echo ""
echo "  sudo -u nft_app git clone <YOUR_REPO_URL> /home/nft_app/nft_platform"
echo "  cd /home/nft_app/nft_platform"
echo ""
echo "Replace <YOUR_REPO_URL> with your GitHub repo URL"
echo ""
read -p "Press Enter once cloned..."

# Step 6: PostgreSQL setup
echo ""
echo "Step 6: Setup PostgreSQL user and database"
echo "=========================================="
echo "Run this on Ubuntu server:"
echo ""
echo "  sudo -u postgres psql"
echo ""
echo "Then paste these SQL commands:"
echo ""
echo "  CREATE USER nft_user WITH PASSWORD 'GiftedForge';"
echo "  CREATE DATABASE nft_db OWNER nft_user;"
echo "  GRANT ALL PRIVILEGES ON DATABASE nft_db TO nft_user;"
echo "  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO nft_user;"
echo "  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO nft_user;"
echo "  \\q"
echo ""
read -p "Press Enter once PostgreSQL is configured..."

# Step 7: Setup Python environment
echo ""
echo "Step 7: Setup Python virtual environment"
echo "=========================================="
echo "Run these on Ubuntu server (in /home/nft_app/nft_platform):"
echo ""
echo "  python3.11 -m venv .venv"
echo "  source .venv/bin/activate"
echo "  pip install --upgrade pip"
echo "  pip install -r requirements.txt"
echo ""
read -p "Press Enter once dependencies installed..."

# Step 8: Copy .env file
echo ""
echo "Step 8: Deploy .env file"
echo "=========================================="
echo "Run this on your Windows machine in the project directory:"
echo ""
echo "  scp .env root@5.252.155.82:/home/nft_app/nft_platform/"
echo ""
read -p "Press Enter once .env is copied..."

# Step 9: Test database connection
echo ""
echo "Step 9: Test database connection"
echo "=========================================="
echo "Run this on Ubuntu server (in /home/nft_app/nft_platform):"
echo ""
echo "  source .venv/bin/activate"
echo "  python test_connection.py"
echo ""
echo "Should show: ✓ Connection successful!"
echo ""
read -p "Press Enter once connection is verified..."

# Step 10: Run migrations
echo ""
echo "Step 10: Run Alembic migrations"
echo "=========================================="
echo "Run this on Ubuntu server (in /home/nft_app/nft_platform):"
echo ""
echo "  source .venv/bin/activate"
echo "  alembic upgrade head"
echo ""
read -p "Press Enter once migrations complete..."

# Step 11: Setup systemd service
echo ""
echo "Step 11: Setup systemd service"
echo "=========================================="
echo "Run this on Ubuntu server:"
echo ""
echo "  sudo cp deployment/systemd/nft-platform.service /etc/systemd/system/"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl enable nft-platform"
echo "  sudo systemctl start nft-platform"
echo "  sudo systemctl status nft-platform"
echo ""
read -p "Press Enter once service is running..."

# Step 12: Setup Nginx reverse proxy
echo ""
echo "Step 12: Setup Nginx reverse proxy (optional)"
echo "=========================================="
echo "Run this on Ubuntu server:"
echo ""
echo "  sudo apt install -y nginx"
echo "  sudo cp deployment/nginx/nft-platform.conf /etc/nginx/sites-available/"
echo "  sudo ln -s /etc/nginx/sites-available/nft-platform.conf /etc/nginx/sites-enabled/"
echo "  sudo systemctl enable nginx"
echo "  sudo systemctl start nginx"
echo ""
echo "Access your app at: http://5.252.155.82"
echo ""

echo ""
echo "=================================================="
echo "✓ Deployment Complete!"
echo "=================================================="
echo ""
echo "Your NFT Platform Backend is now running on:"
echo "  Direct: http://5.252.155.82:8000"
echo "  Via Nginx: http://5.252.155.82"
echo ""
echo "API Documentation: http://5.252.155.82:8000/docs"
echo ""
